Update debug.build.yml

diff --git a/.github/workflows/debug.build.yml b/.github/workflows/debug.build.yml
--- a/.github/workflows/debug.build.yml
+++ b/.github/workflows/debug.build.yml
@@ -53,7 +53,7 @@ jobs:
   package:
     name: Package builds
     runs-on: ubuntu-latest
-    if: success() || failure()
+    # if: success() || failure()
     needs: ['build']
     steps:
       - uses: geode-sdk/build-geode-mod/combine@main
@@ -63,3 +63,14 @@ jobs:
         with:
           name: Build Output
           path: ${{ steps.build.outputs.build-output }}
+  check_and_upload:
+    needs: package
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if Build Output.zip was uploaded
+        run: |
+          if [[ "${{ needs.package.outputs.build-output }}" ]]; then
+            echo "Build Output.zip was uploaded successfully."
+          else
+            echo "Build Output.zip was not uploaded."
+          fi
